version: '3'

services:
    #
    # MySQL
    #
    mysql:
        restart: unless-stopped
        build:
            context: ./.devops/mysql
            dockerfile: ./Dockerfile
        image: prytoegrian/oauth-mysql
        container_name: oauth-mysql
        environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: storage
        expose:
            - 3306
        networks:
            - inner

    #
    # Apache
    #
    web:
        restart: unless-stopped
        build:
            context: ./.devops/web
            dockerfile: ./Dockerfile
        image: prytoegrian/oauth-web
        container_name: oauth-web
        ports:
            - 8080:80
        networks:
            - inner
        links:
            - mysql:mysql
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html

networks:
    inner:
